# официальный образ https://hub.docker.com/_/postgres
services:

  db:
    container_name: postgres
    image: postgres:18.4
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: university
      # https://github.com/docker-library/postgres/pull/1259
      # Change PGDATA in 18+ to /var/lib/postgresql/MAJOR/docker
      PGDATA: "/var/lib/postgresql/18/docker"
    volumes:
      #- ../2. Init Database:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    networks:
      - back-tier

  adminer:
    container_name: adminer
    image: adminer:5.5.1
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge