services:
  nexus:
    image: sonatype/nexus3:3.95.2-alpine
    container_name: nexus
    restart: unless-stopped
    volumes:
      - ./nexus-data:/nexus-data
    ports:
      - 8081-8090:8081-8090
    networks:
      - nexus_net

volumes:
  nexus-data:

networks:
  nexus_net:
    driver: bridge

x-app-meta:
  web:
    port: 8081
    protocol: http